CREATE TABLE IF NOT EXISTS contacts (
  created_at REAL DEFAULT(JULIANDAY(CURRENT_TIMESTAMP)) NOT NULL,
  email TEXT NOT NULL,
  id INTEGER PRIMARY KEY,
  meta BLOB NOT NULL,
  name TEXT NOT NULL,
  phone TEXT NOT NULL
) STRICT
