CREATE TABLE IF NOT EXISTS contacts (
  created_at TEXT DEFAULT CURRENT_TIMESTAMP NOT NULL,
  email TEXT NOT NULL,
  id INTEGER PRIMARY KEY,
  meta BLOB NOT NULL,
  name TEXT NOT NULL,
  phone TEXT NOT NULL,
  updated_at TEXT DEFAULT CURRENT_TIMESTAMP NOT NULL
) STRICT
