// Code generated by "sqlc-gen-zz". DO NOT EDIT.

package q

import (
	"time"
)

type Contact struct {
	CreatedAt time.Time `json:"created_at"`
	Email     string    `json:"email"`
	Id        int64     `json:"id"`
	Meta      []byte    `json:"meta"`
	Name      string    `json:"name"`
	Phone     string    `json:"phone"`
	UpdatedAt time.Time `json:"updated_at"`
}
