// Code generated by "sqlc-gen-zz". DO NOT EDIT.

package q

import (
	"time"

	"github.com/nzoschke/codon/pkg/models"
)

type Contact struct {
	CreatedAt time.Time          `json:"created_at"`
	Email     string             `json:"email"`
	ID        int64              `json:"id"`
	Info      models.ContactInfo `json:"info"`
	Name      string             `json:"name"`
	Phone     string             `json:"phone"`
	UpdatedAt time.Time          `json:"updated_at"`
}

func catalogImports() {
	_ = time.Time{}
}
