// Code generated by "sqlc-gen-zz". DO NOT EDIT.

package q

type Contact struct {
	CreatedAt float64 `json:"created_at"`
	Email     string  `json:"email"`
	Id        int64   `json:"id"`
	Meta      []byte  `json:"meta"`
	Name      string  `json:"name"`
	Phone     string  `json:"phone"`
	UpdatedAt float64 `json:"updated_at"`
}
