// Code generated by "sqlc-gen-zombiezen". DO NOT EDIT.

package q

import (
	"fmt"
	"zombiezen.com/go/sqlite"

	"time"
)

type ContactCreateRes struct {
	CreatedAt time.Time `json:"created_at"`
	Email     string    `json:"email"`
	Id        int64     `json:"id"`
	Meta      []byte    `json:"meta"`
	Name      string    `json:"name"`
	Phone     string    `json:"phone"`
	UpdatedAt time.Time `json:"updated_at"`
}

type ContactCreateParams struct {
	Email string `json:"email"`
	Meta  []byte `json:"meta"`
	Name  string `json:"name"`
	Phone string `json:"phone"`
}

type ContactCreateStmt struct {
	stmt *sqlite.Stmt
}

func ContactCreate(tx *sqlite.Conn) *ContactCreateStmt {
	// Prepare the statement into connection cache
	stmt := tx.Prep(`
INSERT INTO
  contacts (email, meta, name, phone)
VALUES
  (?, ?, ?, ?)
RETURNING
  created_at, email, id, meta, name, phone, updated_at
    `)
	ps := &ContactCreateStmt{stmt: stmt}
	return ps
}

func (ps *ContactCreateStmt) Run(
	params ContactCreateParams,
) (
	res *ContactCreateRes,
	err error,
) {
	defer ps.stmt.Reset()

	// Bind parameters
	ps.stmt.BindText(1, params.Email)
	ps.stmt.BindBytes(2, params.Meta)
	ps.stmt.BindText(3, params.Name)
	ps.stmt.BindText(4, params.Phone)

	// Execute the query
	if hasRow, err := ps.stmt.Step(); err != nil {
		return res, fmt.Errorf("failed to execute {{.Name.Lower}} SQL: %w", err)
	} else if hasRow {
		row := ContactCreateRes{}
		row.CreatedAt = JulianDayToTime(ps.stmt.ColumnFloat(0))
		row.Email = ps.stmt.ColumnText(1)
		row.Id = ps.stmt.ColumnInt64(2)
		row.Meta = StmtBytesByCol(ps.stmt, 3)
		row.Name = ps.stmt.ColumnText(4)
		row.Phone = ps.stmt.ColumnText(5)
		row.UpdatedAt = JulianDayToTime(ps.stmt.ColumnFloat(6))
		res = &row
	}

	return res, nil
}

func OnceContactCreate(
	tx *sqlite.Conn,
	params ContactCreateParams,
) (
	res *ContactCreateRes,
	err error,
) {
	ps := ContactCreate(tx)

	return ps.Run(
		params,
	)
}
