// Code generated by tygo. DO NOT EDIT.

//////////
// source: contact_age.go

export interface ContactAgeStmt {
}

//////////
// source: contact_create.go

export interface ContactCreateRes {
  created_at?: string /* RFC3339 */;
  email?: string;
  id: number /* int64 */;
  meta?: string;
  name: string;
  phone?: string;
}
export interface ContactCreateParams {
  email?: string;
  meta?: string;
  name: string;
  phone?: string;
}
export interface ContactCreateStmt {
}

//////////
// source: contact_delete.go

export interface ContactDeleteStmt {
}

//////////
// source: contact_list.go

export interface ContactListRes {
  created_at?: string /* RFC3339 */;
  email?: string;
  id: number /* int64 */;
  meta?: string;
  name: string;
  phone?: string;
}
export interface ContactListStmt {
}

//////////
// source: contact_read.go

export interface ContactReadRes {
  created_at?: string /* RFC3339 */;
  email?: string;
  id: number /* int64 */;
  meta?: string;
  name: string;
  phone?: string;
}
export interface ContactReadStmt {
}

//////////
// source: contact_update.go

export interface ContactUpdateParams {
  email?: string;
  meta?: string;
  name: string;
  phone?: string;
  id: number /* int64 */;
}
export interface ContactUpdateStmt {
}

//////////
// source: util.go

export const UnixEpochJulianDay = 2440587.5;
