// Code generated by "sqlc-gen-zombiezen". DO NOT EDIT.

package q

import (
	"fmt"
	"zombiezen.com/go/sqlite"

	"time"
)

type UserReadRes struct {
	CreatedAt *time.Time `json:"created_at"`
	Email     string     `json:"email"`
	Id        int64      `json:"id"`
	Name      string     `json:"name"`
}

type UserReadStmt struct {
	stmt *sqlite.Stmt
}

func UserRead(tx *sqlite.Conn) *UserReadStmt {
	// Prepare the statement into connection cache
	stmt := tx.Prep(`
SELECT
  created_at, email, id, name
FROM
  users
WHERE
  id = ?
LIMIT
  1
    `)
	ps := &UserReadStmt{stmt: stmt}
	return ps
}

func (ps *UserReadStmt) Run(
	id int64,
) (
	res *UserReadRes,
	err error,
) {
	defer ps.stmt.Reset()

	// Bind parameters
	ps.stmt.BindInt64(1, id)

	// Execute the query
	if hasRow, err := ps.stmt.Step(); err != nil {
		return res, fmt.Errorf("failed to execute {{.Name.Lower}} SQL: %w", err)
	} else if hasRow {
		row := UserReadRes{}
		isNullCreatedAt := ps.stmt.ColumnIsNull(0)
		if !isNullCreatedAt {
			tmp := JulianDayToTime(ps.stmt.ColumnFloat(0))
			row.CreatedAt = &tmp
		}
		row.Email = ps.stmt.ColumnText(1)
		row.Id = ps.stmt.ColumnInt64(2)
		row.Name = ps.stmt.ColumnText(3)
		res = &row
	}

	return res, nil
}

func OnceUserRead(
	tx *sqlite.Conn,
	id int64,
) (
	res *UserReadRes,
	err error,
) {
	ps := UserRead(tx)

	return ps.Run(
		id,
	)
}
