// Code generated by "sqlc-gen-zombiezen". DO NOT EDIT.

package q

import (
	"fmt"
	"zombiezen.com/go/sqlite"
)

type UserUpdateParams struct {
	Email string `json:"email"`
	Name  string `json:"name"`
	Id    int64  `json:"id"`
}

type UserUpdateStmt struct {
	stmt *sqlite.Stmt
}

func UserUpdate(tx *sqlite.Conn) *UserUpdateStmt {
	// Prepare the statement into connection cache
	stmt := tx.Prep(`
UPDATE
  users
SET
  email = ?,
  name = ?
WHERE
  id = ?
    `)
	ps := &UserUpdateStmt{stmt: stmt}
	return ps
}

func (ps *UserUpdateStmt) Run(
	params UserUpdateParams,
) (
	err error,
) {
	defer ps.stmt.Reset()

	// Bind parameters
	ps.stmt.BindText(1, params.Email)
	ps.stmt.BindText(2, params.Name)
	ps.stmt.BindInt64(3, params.Id)

	// Execute the query
	if _, err := ps.stmt.Step(); err != nil {
		return fmt.Errorf("failed to execute userupdate SQL: %w", err)
	}

	return nil
}

func OnceUserUpdate(
	tx *sqlite.Conn,
	params UserUpdateParams,
) (
	err error,
) {
	ps := UserUpdate(tx)

	return ps.Run(
		params,
	)
}
